version: '3'
services:
  auth:
    image: "amstee/src-cut-auth:${TAG}"
    ports:
    - 8080:8080
  appoitment:
    image: "amstee/src-cut-appointment:${TAG}"
    ports:
      -  8085:8080
    links:
      - auth
  barber:
    image: "amstee/src-cut-barber:${TAG}"
    ports:
      - 8082:8080
    links:
      - auth
  rating:
    image: "amstee/src-cut-rating:${TAG}"
    ports:
      - 8083:8080
    links:
      - auth
  salon:
    image: "amstee/src-cut-salon:${TAG}"
    ports:
      - 8084:8080
    links:
      - auth
  user:
    image: "amstee/src-cut-user:${TAG}"
    ports:
      - 8081:8080
    links:
      - auth


