version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    container_name: "nginx" # _${TAG}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  auth:
    image: "amstee/easy-cut-auth:${TAG}"
    container_name: "auth" # _${TAG}
    expose:
      - 8080
  user:
    image: "amstee/easy-cut-user:${TAG}"
    container_name: "user"  # _${TAG}
    expose:
      - 8080
    links:
      - auth


