version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    container_name: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.crt:/etc/nginx/cert.crt
      - ./cert.key:/etc/nginx/cert.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - auth
      - user
      - barber
      - elasticsearch
  auth:
    image: "amstee/easy-cut-auth:${TAG}"
    container_name: "auth"
    expose:
      - 8080
  user:
    image: "amstee/easy-cut-user:${TAG}"
    container_name: "user"
    expose:
      - 8080
    environment:
      API_CLIENT_ID: "${API_CLIENT_ID}"
      API_CLIENT_SECRET: "${API_CLIENT_SECRET}"
    links:
      - auth
  barber:
    image: "amstee/easy-cut-barber:${TAG}"
    container_name: "barber"
    expose:
    - 8080
    depends_on:
    - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: "elastic"
    environment:
      - "discovery.type=single-node"
      - "network.host=0.0.0.0"
    expose:
      - 9200

