apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: dev
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: http2
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: amstee/easy-cut-auth:dev
        ports:
        - containerPort: 8080
