apiVersion: v1
kind: Service
metadata:
  name: elastic-service
  namespace: dev
  labels:
    app: elastic
spec:
  selector:
    app: elastic
  ports:
  - name: default
    port: 9200
    targetPort: 9200
  - name: default2
    port: 9300
    targetPort: 9300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  namespace: dev
  labels:
    app: elastic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
      - name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
        ports:
        - containerPort: 8080
        env:
          - "discovery.type=single-node"
          - "network.host=0.0.0.0"