apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dev
data:
  nginx.conf : |
    worker_processes 1;
    events { worker_connections 1024; }
    http {
        sendfile on;
        upstream docker-auth {
            server auth-service;
        }
        upstream docker-user {
            server user-service;
        }
        server {
            listen 80;
            location /auth {
                return 302 /auth/;
            }
            location /user {
                return 302 /user/;
            }
            location /auth/ {
                proxy_pass         http://docker-auth/;
                proxy_redirect     off;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;
            }
            location /user/ {
                proxy_pass         http://docker-user/;
                proxy_redirect     off;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;
            }
        }
    }