apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dev
data:
  nginx.conf : |
  worker_processes 1;

  events { worker_connections 2048; }

  http {

  sendfile on;

  upstream docker-auth {
  server auth-service;
  }

  upstream docker-user {
  server user-service;
  }

  upstream docker-es {
  server elasticsearch:9200;
  }

  upstream docker-salon {
  server salon-service;
  }

  upstream docker-barber {
  server barber-service;
  }

  upstream docker-perms {
  server perms-service;
  }

  upstream docker-appointment {
  server appointment-service;
  }

  upstream docker-rating {
  server rating-service;
  }

  server {
  server_name http-easy-cut;
  listen 80;

  location /auth {
  return 302 /auth/;
  }

  location /user {
  return 302 /user/;
  }

  location /barber {
  return 302 /barber/;
  }

  location /salon {
  return 302 /salon/;
  }

  location /es {
  return 302 /es/;
  }

  location /appointment {
  return 302 /appointment/;
  }

  location /rating {
  return 302 /rating/;
  }

  location /perms {
  return 302 /perms/;
  }

  location /auth/ {
  proxy_pass         http://docker-auth/;
  proxy_redirect     off;
  proxy_set_header   Host $host;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Host $server_name;
  }

  location /es/ {
  proxy_pass         http://docker-es/;
  proxy_redirect     off;
  proxy_set_header   Host $host;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Host $server_name;
  }

  location /user/ {
  proxy_pass         http://docker-user/;
  proxy_redirect     off;
  proxy_set_header   Host $host;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Host $server_name;
  }

  location /barber/ {
  proxy_pass         http://docker-barber/;
  proxy_redirect     off;
  proxy_set_header   Host $host;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Host $server_name;
  }

  location /salon/ {
  proxy_pass         http://docker-salon/;
  proxy_redirect     off;
  proxy_set_header   Host $host;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Host $server_name;
  }

  location /perms/ {
  proxy_pass         http://docker-perms/;
  proxy_redirect     off;
  proxy_set_header   Host $host;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Host $server_name;
  }

  location /rating/ {
  proxy_pass         http://docker-rating/;
  proxy_redirect     off;
  proxy_set_header   Host $host;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Host $server_name;
  }

  location /appointment/ {
  proxy_pass         http://docker-appointment/;
  proxy_redirect     off;
  proxy_set_header   Host $host;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Host $server_name;
  }
  }
  }