version: '3'
networks:
  services:
  proxy:
services:
  nginx:
    image: nginx:1.15-alpine
    container_name: "nginx"
    volumes:
      - "/home/docker/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints: [node.role == manager]
    restart: always
    networks:
      - services
      - proxy
  auth:
    image: "amstee/easy-cut-auth:${TAG}"
    container_name: "auth"
    restart: always
    deploy:
      replicas: 2
    networks:
      - services
  user:
    image: "amstee/easy-cut-user:${TAG}"
    container_name: "user"
    restart: always
    deploy:
      replicas: 2
    links:
      - auth
    networks:
      - services
